"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import "./style.css"
 const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const navLinks = [
  {id:'1' , text:'Login',  href:'/login'},
  {id:'2' ,text:'Register', href:'/register'},
  {id:'3' ,text:'Forgot Password', href:'/forgot-password'}
]

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()
  return (
    <html lang="en">
      
      <body>
       <main>
        {navLinks.map((link)=>{
          const isActive = pathname == link.href && pathname.startsWith(link.href) && pathname !== "/"
         return <Link className={isActive ? "font-bold color-black mr-4" : "font-regular color-blue mr-4"} key={link.id} href={link.href}>{link.text}</Link>
        })}
         {children}
        </main>
        <footer style={{
        backgroundColor:"#3bb54a",
        padding:10,
        color:"#fff"
      }}>Footer</footer>
    </body>
      
    </html>
  )
}