export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
      <header style={{
        backgroundColor:"#1170ff",
        padding:10,
        color:"#fff"
      }}>Header</header>
       <main>
         {children}
        </main>
        <footer style={{
        backgroundColor:"#3bb54a",
        padding:10,
        color:"#fff"
      }}>Footer</footer>
    </body>
      
    </html>
  )
}
